### ISSUE TITLE
Can you provide a pure pytorch version?

### ISSUE THREAD

**Issue by Ken1256** [xtudbxk/TMP#1]
tmp pytorch version

**Comment by xtudbxk** [comment]
While pytorch supports little for parallelled pixel-to-pixel comparisons, it would be extremely slow for a pure pytorch tmp algorithm. Thus, we have no plan to implement the such a algorithm.

However, you can directly call the tmp algorithm with pure pytorch code by using the function defined in "[basicsr/archs/tmp/tmpwrapper.py](https://github.com/xtudbxk/TMP/blob/main/basicsr/archs/tmp/tmpwrapper.py)". The inherited offsets will be updated in the "offsets" param. For details about the usage of tmp function, please refer to [basicsr/archs/tmpalign_util.py](https://github.com/xtudbxk/TMP/blob/main/basicsr/archs/tmpalign_util.py)

We utilize the ninja to seamlessly integrate the tmp cuda version with the pytorch. For more details about the cuda extension of pytorch, please refer to [https://pytorch.org/tutorials/advanced/cpp_extension.html](https://pytorch.org/tutorials/advanced/cpp_extension.html)
