### ISSUE TITLE
运行时间

### ISSUE THREAD

**Issue by fzuqxt** [xtudbxk/TMP#3]
你好作者，请问下您论文中的runtimes是如何测得的

**Comment by xtudbxk** [comment]
We evaluate the runtime of our method by processing a sequence of five consecutive frames, each with a resolution of 180x320, using the V100 GPU. The reported results are the average of ten repetitions of this process.

**Comment by fzuqxt** [comment]
谢谢，请问测的代码是直接加在arch文件里吗

**Comment by xtudbxk** [comment]
Yes, you can evalutate the runtime by adding code into the arch file.

The code for evaluating the network will come with futher version. 
Thus, currently, you have to add the code by yourself. 
A simple way to implement it is to use time.time() with torch.cuda.synchronize().
Please search on the internet or leverage open-source LLM to help you ~
