### ISSUE TITLE
Code running environment issues

### ISSUE THREAD

**Issue by JEDA836** [xtudbxk/TMP#4]
Hello, I would like to ask about the code running environment. After downloading the library according to the requirements.txt, you will encounter the following problems when running the code. Have you encountered this problem? Or your other environments such as CUDA version What is it

**Comment by JEDA836** [comment]
![image](https://github.com/xtudbxk/TMP/assets/94223976/9e50a417-a4ed-4673-b9ff-146fd5b30c9e)

**Comment by xtudbxk** [comment]
It seems the issue related to the CUDA environment.

I use cuda 11.3 with pytorch 1.10. 

Hope this can help.
