### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by hansomxue99** [xtudbxk/TMP#5]
Dear Authors, thanks for your nice work. 
I wonder if there is a BI version pretrained model for TMP network.

**Comment by xtudbxk** [comment]
We shared one pretrained model using onedrive in the homepage. 

Although it was named by "BD_", it actually is a model for BI degrdation. We have corrected its name.

**Comment by hansomxue99** [comment]
Thanks for your replying. Will you release the pretrained model for BD degradation?

**Comment by xtudbxk** [comment]
Yes, we will.
But it would not be soon since we are preparing additional experiments.

**Comment by hansomxue99** [comment]
Thank you for your response. I appreciate your efforts in preparing additional experiments. I'll be looking forward to the release of the pretrained model for BD degradation whenever it becomes available.
